layout_spectrum: 0.4802867
typography_spectrum: 0.4767025
color:
  saturation: 0.9139785
  lightness: 0.781362
  brandStrength: 0.7526882
  rhythmicContrast: 0.5017921
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Steve Fox AST
